### ISSUE TITLE
Crashing at what seem when I push shift

### ISSUE THREAD

**Issue by RetroAech** [CottonMC/DynaGear#3]
https://paste.ee/p/jK8S1

Its late at night and i don't feel like typing out all that info, I crash when I hit shift and i think it is cause of a mod that has to do with holding shift to see more info, yah know? But yeah, any questions I'll respond!

**Comment by Boundarybreaker** [comment]
Yeah, that looks like an incompat with Enchanted Tooltips. I'll try to talk to the dev, but it seems like something on their side.

**Comment by Boundarybreaker** [comment]
It looks like you might also be using an outdated of Enchanted Tooltips. I don't think there's anything I can do here.
