### ISSUE TITLE
update to 1.16

### ISSUE THREAD

**Issue by Nathan22211** [CottonMC/DynaGear#7]
**Is your feature request related to a problem? Please describe.**
an update is needed to 1.16

**Describe the solution you'd like**
an update, I'd imagine tools haven't changed much

**Describe alternatives you've considered**
this is the only mod that does data-driven vanilla tools, and I'm not counting suludom. currently, there are no alternatives to this to my knowledge

**Additional context**
got nothing for this, more of an update request

**Comment by LemmaEOF** [comment]
already done in #6, might have forgotten to publish
